spring:
  application:
    name: doudou-freechat
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

server:
  port: 9001

# 配置 Mybatis.xml 位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

ignored:
  urls:
    - /
    - /error
    - /favicon.ico
    - /auth/login
    - /auth/register
    - /auth/verCode
    - /common/pre

jwt:
  token: token # cookie字段名
  secret: doudou@freechat # 加密key
  expiration: 604800 # jwt的超期限时间(60*60*24*7)