spring:
  application:
    name: doudou-freechat
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  cache:
    type: redis
  mail:
    # 邮件服务器地址
    host: smtp.gmail.com
    # smtp的指定端口 使用465要将protocol改为smtps
    port: 587
    # 协议 默认就是smtp
    protocol: smtp
    # 编码格式 默认就是utf-8
    default-encoding: utf-8
    username: freechat.bilinstore@gmail.com
    password: qlssjjctujexicwu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9001
  servlet:
    context-path: /doudou

# 配置 Mybatis.xml 位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

ignored:
  urls:
    - /
    - /error
    - /favicon.ico
    - /doudou/error
    - /doudou/favicon.ico
    - /doudou/auth/login
    - /doudou/auth/register
    - /doudou/auth/verCode
    - /doudou/common/pre

jwt:
  token: token # cookie字段名
  secret: doudou@freechat # 加密key
  expiration: 604800 # jwt的超期限时间(60*60*24*7)
