spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/free_chat?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

# 配置 Mybatis.xml 位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

ignored:
  urls:
    - /auth/login
    - /auth/register
    - /auth/verCode
    - /common/pre

jwt:
  token: token # cookie字段名
  secret: doudou@freechat # 加密key
  expiration: 604800 # jwt的超期限时间(60*60*24*7)