name: Deploy Spring Boot App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取最新提交的代码
        uses: actions/checkout@v3

      - name: 设置jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: 项目打包
        run: mvn -B package

#       - name: 删除旧的jar包以及运行脚本
#         run: sshpass -p ${{secrets.SSH_PASSWORD}} ssh -o StrictHostKeyChecking=no root@${{secrets.HOST}} "cd /www/wwwroot/freechat.bilinstore.com/springboot && rm -rf ./*"

#       - name: 上传jar包和启动脚本到服务器中
#         run: sshpass -p ${{secrets.SSH_PASSWORD}} scp -r -o StrictHostKeyChecking=no ./target/freeChat-0.0.1.jar ./run.sh root@${{secrets.HOST}}:/www/wwwroot/freechat.bilinstore.com/springboot

#       - name: 启动项目
#         run: sshpass -p ${{secrets.SSH_PASSWORD}} ssh -o StrictHostKeyChecking=no root@${{secrets.HOST}} "cd /www/wwwroot/freechat.bilinstore.com/springboot && chmod +x run.sh && ./run.sh"
